### ISSUE TITLE
Bug: No reset of metrics after each check run

### ISSUE THREAD

**Issue by y-eight** [caas-team/sparrow#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the sparrow is exposing metrics for each check. In this example, I will reference the latency check but this is related to all the checks.

The latency check provides metrics with the statuscode as metadata in the metric itself, eg.:
`sparrow_latency_duration_seconds{status="200",target="https://xyz.telekom.de/"} 0.1750766`

If in one of the previous runs/check intervall the status was not 200 (eg. 500) the metric will be exposed with `status="500"`.
If the current run is getting a 200 status code the metric will be exposed with `status="200"`. The metric with `status="500"` is still present. The problem is that the sparrow is not exposing the last state. This is misleading since the status 500 is not the last state.

### Expected Behavior

The prom metrics should represent the last state of the check.
Therefore the old metrics should be cleared before updating with the current state.

### Relevant logs and/or screenshots, environment information, etc.

![image](https://github.com/caas-team/sparrow/assets/26814413/d20758ea-8b4b-4127-9a97-592e2c131e0f)

**Comment by lvlcn-t** [comment]
@y-eight While this bug is not exactly the same as #77, it's quite similar and I'd see it as one bigger issue that should be addressed in the near future.

**Comment by puffitos** [comment]
The problem here is quite another; we are probably misusing prometheus metrics. A more appropriate solution would be to use a counter with the status and url labels (to count how many requests were successful or not) and just a latency_duration_seconds, which just returns how much time the last call needed to finish.

This way, we always return the core information of the check (which is the *latency*) and also expose some additional information.
