### ISSUE TITLE
Feature: Dynamically switch logging verbosity

### ISSUE THREAD

**Issue by y-eight** [caas-team/sparrow#28]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Problem Description

The logger does have a fixed verbosity. 

The logging verbosity should be switchable during the runtime but at least by defining an environment variable.

**Comment by lvlcn-t** [comment]
Imo modifying the verbosity during runtime wouldn't be a good idea, especially with k8s, because altering environment variables on the fly isn't straightforward; it requires restarting the pod to remount the secret -> startup config

If we were to introduce it during runtime, it would require changes to the runtime config, which currently serves the purpose of managing checks so more substantial alterations to sparrows behavior, rather than minor settings.

I think it makes more sense to set the verbosity on startup. This way, we don't have to deal with the trouble of changing it during runtime.
